### ISSUE TITLE
Duplicated issues

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#133]
Some repositories have duplicated issues, see for example `catboost/catboost`:  #863 and #1860 are duplicated.

<img width="759" alt="image" src="https://github.com/lucavallin/first-issue/assets/14332663/7a54f144-db54-4f9a-841e-86f2273caa42">

**Comment by cloudhoy** [comment]
Hi there! I'd like to handle this issue.

**Comment by lucavallin** [comment]
Hey @cloudhoy! Please go ahead ;)
