### ISSUE TITLE
Text overflows when issue title has long words

### ISSUE THREAD

**Issue by cloudhoy** [lucavallin/first-issue#138]
Text overflow occurs for issue titles with long words. See for example `mattermost/mattermost` in the gif below:

![issue-long-word-text-overflow](https://github.com/lucavallin/first-issue/assets/138202184/8b9c524f-bc5e-4c2f-9408-ac84754b39ae)

**Comment by Clarerodev** [comment]
Hi! I'd like to resolve this issue. I think we can solve this with a word break. 🙂
