### ISSUE TITLE
Repository list does not take up full width of content area

### ISSUE THREAD

**Issue by cloudhoy** [lucavallin/first-issue#141]
See `https://firstissue.dev/language/lua/` page for example. In the screenshot below, the repository list does not take up the full width of the content area (empty space indicated by the red rectangle).

![image](https://github.com/lucavallin/first-issue/assets/138202184/e8e7c01b-6175-442f-ba73-dd7a9c9b1f03)

**Comment by Senatrius** [comment]
This should be as simple as adding `grow` class to the repo list container since the parent is a flex container. Will take a look.
