### ISSUE TITLE
Pipeline build error

### ISSUE THREAD

**Issue by cloudhoy** [lucavallin/first-issue#149]
An error occurred during the build process after merging PR #139:

![image](https://github.com/lucavallin/first-issue/assets/138202184/bf5b9b04-d53e-43f9-8dec-923f8ea3b3c9)

> Hey @cloudhoy! I merged the PR but in the pipeline an error seems to come up, my bad, I should have enabled Actions on PRs. Would you be able to open a new PR and have a look at https://github.com/lucavallin/first-issue/actions/runs/5793919555/job/15702527904? 🙏🏼  

_Originally posted by @lucavallin in https://github.com/lucavallin/first-issue/issues/139#issuecomment-1669046414_

**Comment by cloudhoy** [comment]
Hi @lucavallin! This error occurs on Node.js versions older than `18`, which does not have a [native fetch API](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental). Seems like we're using version `16` right now.
![image](https://github.com/lucavallin/first-issue/assets/138202184/02fd289e-d875-4900-89ac-25acf711d04a)

To fix this, we could either update to Node.js version to `18`, or we could provide our own `fetch` implementation with the [node-fetch](https://www.npmjs.com/package/node-fetch).

What do you think is the best way forward?

**Comment by lucavallin** [comment]
Hey @cloudhoy! Thanks for checking this. I would say Node 18 it is!
