### ISSUE TITLE
Hitting secondary rate limit during data generation

### ISSUE THREAD

**Issue by cloudhoy** [lucavallin/first-issue#151]
> Hey @cloudhoy! No token errors in the workflow, however, we are being rate-limited, see https://github.com/lucavallin/first-issue/actions/runs/5815296740/job/15766591898#step:7:27. How would you address this?

_Originally posted by @lucavallin in https://github.com/lucavallin/first-issue/issues/150#issuecomment-1673621813_

**Comment by lucavallin** [comment]
@cloudhoy pinging you just to let you know the workflow is doing great. But more importantly: you got the requests we make down to 1/3 and the pipeline now takes 6 minutes instead of 26! 😲

Congratulations, excellent work.

**Comment by cloudhoy** [comment]
Hey @lucavallin, that's awesome to hear! Glad to help! 😁
