### ISSUE TITLE
Spread the word about firstissue.dev

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#158]
I think `first-issue` should integrate with social networks so that we can increase our reach. A possible strategy would be to post a link to a "random" repository with new issues (or some other metric) at every deployment. The platforms could be:

- Reddit
- Twitter/X
- LinkedIn
- ...
- I am not sure which ones next because I only really use Reddit and LinkedIn.

Doing this requires registering the accounts, put together some script that publishes posts (or use an intermediary that can take care of the implementation details for each platform for us) and then publishing the post as the last step in the deployment pipeline.

**Comment by AustinMay1** [comment]
Hey! This looks like something I would like to work on. Hopefully I am understanding this correctly:

- Create social accounts for firstissue.
- Every new deployment, post a link to a random/new repo with open issues to each social account.

Please let me know if this is what you are looking for, I can get started right away.

**Comment by lucavallin** [comment]
Hey Austin! That sounds about right. The only difference is that I would first find out which socials we want to post to, and then I can create the accounts for them ;)

**Comment by AustinMay1** [comment]
Sure thing! Reddit, Twitter & LinkedIn sound like good starting points. They all look to have some sort of free API. There seems to be quite a few options for a consolidated posting service, they are mostly paid products however. It looks like you are using github actions as your deplyoment pipeline, is this correct?

**Comment by AustinMay1** [comment]
To be honest the majority of them are pretty pricey, Hootsuite and Ayrshare being some of the most popular ones (and offer an API) start around $80-90 USD a month. Ayrshare has a free tier which allows up to 20 posts per month. They both support pretty much all social medias. I've linked them below so you can check them out:

[https://www.hootsuite.com/](Hootsuite)
[https://www.ayrshare.com/](Ayrshare)

**Comment by lucavallin** [comment]
Hey @AustinMay1! I gave it some thought over the weekend and I am thinking I am not sure anymore social networks is the way to go. A better approach might be to find "fans" and "partners": people interested in open source, tech newsletters and blogs that might want to write about and share this project. What do you think? Do you know of any interesting ones?

**Comment by AustinMay1** [comment]
Sure, no problem. Patreon is a service that allows you to build a "fan base", members pay a monthly fee (tiered subscriptions) to support the project, which you can also make private posts to. Ive seen a few OS repositories use this. As far as getting other people to write about it, that would probably involve reaching out to some tech "influencers" or other OS communities on YouTube or Twitter. Medium is a blogging site that alot of tech articles are written on. Or you could maybe integrate a blogging platform into firstissue and with some good SEO might drive in some good traffic. Creating a Discord server is another option.

**Comment by lucavallin** [comment]
Hey @AustinMay1! Thanks for the input. I am going to publish a post on https://cavall.in soon enough. In the meantime, I think it'd be good to identify here:

- "awesome" repos we can add `first-issue` to
- Websites and people to reach out to for support
- A discord server is an option but we might need a few more people for that

What do you think?

**Comment by AustinMay1** [comment]
That sounds good to me! I can start looking around and report back with my findings in a couple of days if you're okay with that.

**Comment by lucavallin** [comment]
Great plan! Thanks!

**Comment by AustinMay1** [comment]
Hey @lucavallin, hope all is well,

Here are some resources/people I found that can be reached/contributed to. 

### Influencers / Communities 
These are just a few people I follow/interact with

YourAverageTechBro - https://www.youtube.com/@YourAverageTechBro
Conaticus - https://www.youtube.com/@conaticus
Hitesh Choudhary - https://www.youtube.com/@HiteshChoudharydotcom
Josh Tried Coding - https://www.youtube.com/@joshtriedcoding
Programmers Hangout Discord - https://discord.gg/programming
Programmer Humor - https://discord.gg/rph
r/opensource - https://www.reddit.com/r/opensource/

### Awesome Lists
https://awesomeopensource.com/
https://github.com/unicodeveloper/awesome-opensource-apps

Not finding much in terms of awesome-lists for opensource, could make one? A list that provides several OS resources, guidelines, etc.

### Other
https://forum.freecodecamp.org/latest
https://medium.com/
https://dev.to/

Lots of developers write blogs on Medium, fcc, and Dev.to. Maybe creating an "open source guide" could be of some value.

**Comment by lucavallin** [comment]
Hey @AustinMay1, great job, thanks for all the info! I am thinking you could create some doc in the repo documenting this, that way you'd appear in the list of contributors of the repo 😊

**Comment by lucavallin** [comment]
I think that's a great idea, go ahead!
