### ISSUE TITLE
Review UI & UX

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#17]
The UI is fine at the moment, but some alignments are wonky and the UX could use some polishing.

**Comment by thebarshablog** [comment]
Would love to add some value in this regard. @lucavallin

**Comment by lucavallin** [comment]
Hi @thebarshablog! Thanks for your interest in the issue. Sounds good to me, feel free to look into what can be improved and make a pull request for it. At this time we're using Tailwind for easier CSS and I am looking into adding some components from https://daisyui.com - we could replace most of the existing ones with those from DaisyUI.

**Comment by thebarshablog** [comment]
Thanks once again @lucavallin for assigning me on this. And, I'll have to go through the necessary things for making things better.
