### ISSUE TITLE
Add trending repositories and repositories by topic to list

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#18]
It would be nice to scrape trending repositories everyday and add the ones meeting the criteria to the list. Unfortunately there is no API from GitHub for this, and the third-party solutions don't seem to work anymore, but we'll keep this issue here for the future. Same for discovering repositories by topic.

**Comment by thebarshablog** [comment]
Hey @lucavallin, I'd love to take on this task of updating trending repositories everyday.
I spend quite a time everyday looking for trending repositories on various domains and the domains of my interest too.

**Comment by thebarshablog** [comment]
As of now, we can manually add trending repos while working towards using a solution that automates the process.
Does that sound fine?

**Comment by lucavallin** [comment]
@thebarshablog Hi Barsha, thanks for your message! Sounds good to me, I think doing this manually is the only way at this time. Feel free to create a PR any time you'd like to add repositories to the list!

**Comment by thebarshablog** [comment]
Thank you so much @lucavallin. 
I'll do the needful.

**Comment by thebarshablog** [comment]
Hey @lucavallin I'm keep my beliefs high to contribute to this repo before the year ends.

**Comment by thebarshablog** [comment]
@lucavallin created my 1st pull request by adding a repository that meets our firstissue criteria list mentioned under the README.md file
