### ISSUE TITLE
List sponsors in UI

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#181]
It would be nice to have a small section in the "sidebar" to list sponsors of the project. Current sponsors are:

- Myself, [cavall.in](https://cavall.in)

**Comment by NmSand** [comment]
Hi! Can I opened a PR for this issue. Let me know if there are other changes you'd like me to make @lucavallin

**Comment by lucavallin** [comment]
Hey @NmSand ! Thanks for the interest. I figured out this is not relevant at the moment, happy to re-open it eventually. Thanks!
