### ISSUE TITLE
Implement redesign

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#182]
@chidame is working on a redesign for the website. Once she's done with it, I'll need help implementing it. Leave a comment in this issue if you're interested in helping when the time comes.

**Comment by Neel0305** [comment]
interested

**Comment by Facelift2376** [comment]
interested

**Comment by Hithesh-k1** [comment]
I'm on it

**Comment by parinitapatil** [comment]
I am eager to address this matter.

**Comment by david-solomon-henshaw** [comment]
interested.

**Comment by parinitapatil** [comment]
Hey, I'm not really sure if what I will be submitting counts towards Hacktoberfest. Do you have any idea?

**Comment by Kirtishukla2004** [comment]
Is this implementation currently underway? I'm genuinely intrigued and would like to know more
