### ISSUE TITLE
Improve design of repository item

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#188]
Repository items currently look like this:

![Image](https://github.com/lucavallin/first-issue/assets/14332663/ecd7f7e7-8ce1-473a-96ec-8206717f09fb)

- The font is all different
- Hard to read
- The title of different issues has different lengths and it looks all wonky

Feel free to look into this and come up with something that looks better!

**Comment by Vivek-04022001** [comment]
Can I contribute to this issue?

**Comment by AMalfez** [comment]
Hey @lucavallin !
Can you assign it to me for hacktoberfest?

**Comment by Vivek-04022001** [comment]
@lucavallin , I have done changes to make it looks better 
![image](https://github.com/lucavallin/first-issue/assets/91373023/dae0433f-a347-44e3-95c4-f6d367f4a13e)
