### ISSUE TITLE
Filter repositories in AppData context and finish search bar

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#191]
We are currently filtering repositories in different places, for example:

- [pages/index.tsx](https://github.com/lucavallin/first-issue/blob/main/pages/index.tsx)
- [pages/tag/[tag].tsx](https://github.com/lucavallin/first-issue/blob/main/pages/tag/[tag].tsx)
- [pages/language/[tag].tsx](https://github.com/lucavallin/first-issue/blob/main/pages/language/[tag].tsx)

I think this should be done in the [AppDataContext](https://github.com/lucavallin/first-issue/blob/main/context/AppDataContext.tsx) so that all the repositories we get from there are already filtered. 

This will allow a nicer implementation of the search bar, which is currently half-done [here](https://github.com/lucavallin/first-issue/blob/main/components/SearchBar.tsx). What is missing is to use the query users enter to filter repositories including only those where the query appears in the repository name or owner, topic, issue title. Also, we should use Kbar or Algolia to do the searching.

**Comment by VALiUMgithub** [comment]
Hey Lucavallin, can I work on this issue?

**Comment by lucavallin** [comment]
Hey @VALiUMgithub, feel free to work on it and open a PR!

**Comment by VALiUMgithub** [comment]
Hey @lucavallin, I have completed the task and have opened a PR. Can you kindly check?
