### ISSUE TITLE
Update 404 page

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#192]
The 404 page doesn't appear often, but when it does, it looks out of place:

![Image](https://github.com/lucavallin/first-issue/assets/14332663/816fee4a-8049-4a8c-9a84-383196ddfed6)

Let's discuss ideas and update itso it looks nice!

**Comment by Jagpreet153** [comment]
Hi, @lucavallin 
hope this comment find you in good health 
I would like to contribute and resolve the problem , could you please explain the issue in detail that you want to center the 404 tag or you like to change the whole ui of the page??

**Comment by AbhiPatel10** [comment]
I think you should make a new custom 404 page, if there is anything wrong happen then redirect to that page.

**Comment by Vivek-04022001** [comment]
Can I work on this issue

**Comment by lucavallin** [comment]
@Jagpreet153 It could be centered, that would already make it better. Alternatively, it could be something different, for example we could show an empty repository list. @Vivek-04022001 @AbhiPatel10  Feel free to sync with @Jagpreet153 to work on this ;)

**Comment by Vivek-04022001** [comment]
![image](https://github.com/lucavallin/first-issue/assets/91373023/3236f958-d771-493e-9cfe-fa533837e55f)

_how it looks, do you want to add something here @lucavallin . _ I have done some minor modification in tailwind.config file to get a 5xl text size. It's just a single line modification.

**Comment by Vivek-04022001** [comment]
I would like to request your design advice for mobile devices.

**Comment by AbhiPatel10** [comment]
I think you should make a different page for 404 and redirect to that page if something wrong happened.

**Comment by Vivek-04022001** [comment]
@AbhiPatel10 , okay i will try

**Comment by Vivek-04022001** [comment]
@lucavallin, please provide your recommendation. @AbhiPatel10 suggested redirecting to a new "not-found" page. Do you also prefer a redesign of the "not-found" component?

**Comment by lucavallin** [comment]
Hey @Vivek-04022001! Given that the main layout shows filters for the repo list but on the 404 there are no repos, it probably makes sense to have a 404 page that shows only the 404 message.

**Comment by Vivek-04022001** [comment]
@lucavallin, sounds good! I'll create a separate page for the 404 error. Is there anything else you'd like me to consider?

**Comment by Vivek-04022001** [comment]
![image](https://github.com/lucavallin/first-issue/assets/91373023/bfea4d62-6e18-40e0-9673-bfc731a3aef3)
@lucavallin , is it looks good?

**Comment by Vivek-04022001** [comment]
But I'm afraid, the approach I have used is not good : can you please check the code ,right here 
```
export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const shouldRenderComponents = router.pathname === "/";
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AppDataProvider>
        <main className={`${inter.variable} font-sans`}>
          {shouldRenderComponents ? (
            <>
              <SponsorsBar />
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </>
          ) : (
// 👉Not found component renders only when the conditition is fullfilled.
            <NotFound />
          )}
        </main>
      </AppDataProvider>
    </>
  );
}
```

**Comment by lucavallin** [comment]
Hey @Vivek-04022001 ! Yes, looks good, thanks for working on this! I have a few comments, please open a PR so I can add them there!

**Comment by Vivek-04022001** [comment]
@lucavallin , I have created the pull request. You can check my code now.

**Comment by AbhiPatel10** [comment]
@Vivek-04022001 add close #192 in your pr so Your pr will connected to this Issue

**Comment by Vivek-04022001** [comment]
@AbhiPatel10 , sorry I don't know how to do this? But I have created a pull request. Can you please check. Did i do something wrong?

**Comment by Armaan48985** [comment]
Hii, i am seeing that you want to make a 404 error page, please assign it to me , i will make it so much better.
