### ISSUE TITLE
Navigation improvements on mobile

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#194]
On mobile the menu takes a lot of space and users needs to scroll a while before getting to the list of repositories, see:

![Image](https://github.com/lucavallin/first-issue/assets/14332663/150cd89c-4624-4755-b5b2-375e969218d1)

I suggest the following:

- When a tag or language is selected, the page should scroll automatically to the repository list (could be done with a URL anchor)
- Make it possible to collapse language/tags and open the list only when the section title is clicked.

**Comment by Abhinavxox** [comment]
@lucavallin 
Can you assign me this issue? I have a great idea to solve this.
I will make the language tabs collapsible and also make it scroll automatically to the repository list.

**Comment by Abhinavxox** [comment]
@lucavallin I have made these changes. Is this what you want for the collapse feature or should I make some changes?

[Screencast from 02-10-23 01:33:25 PM +0545.webm](https://github.com/lucavallin/first-issue/assets/72064600/897d1962-d130-4d3b-bfe1-4593a31754cc)

**Comment by lucavallin** [comment]
@Abhinavxox Looks great, see comments in PR ;)

**Comment by lucavallin** [comment]
Closed by #199.
