### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#195]
The performance of the website is not the best, understandably so, given that it is a static website loading ~1.5MB of json data. This is not the only thing that needs addressing, however:

- Run pagespeed or a similar too
- Find performance issues that can be improved
- Address those issues
- Think of a way to reduce the impact of the json data (maybe not possible? maybe it can be loaded in chunks?)

**Comment by Vivek-04022001** [comment]
Can you please assign this task to me?
