### ISSUE TITLE
TailwindCSS best practices

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#205]
We have done a good job at writing quality code, but it is important to always review the state of the codebase to improve it and update itL

- Are we following TailwindCSS' best practices?
- Is our use of TailwindCSS up-to-date?

This is an on-going "issue" that will remain open: do you see anything that could be improved? Let us know and feel free to open a pull request.

**Comment by Vivek-04022001** [comment]
1. I’ve pinpointed a limitation in the Tailwind.config.js file. The color palette was previously fixed, restricting contributors from making direct modifications. To address this, I’ve expanded the color palette to align with TailwindCSS guidelines. This improvement now provides contributors with the flexibility to incorporate a wide array of colors. Below is the revised code:

2. Additionally, I’ve noticed that several contributors are attempting to incorporate various colors into the components. To streamline this process, I’ve made necessary adjustments within the components themselves.

![image](https://github.com/lucavallin/first-issue/assets/91373023/bb88fe0e-93d0-4aa7-9b39-d0b6a6b162c0)

**Comment by Vivek-04022001** [comment]
@lucavallin , Can i send you a pull request for this particular change

**Comment by Vivek-04022001** [comment]
**Previous code look like this inside the taiwind.config.js file**
```
 theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", ...fontFamily.sans]
      }
    },
```

**But if you give me a change , I can modify the code** 
```
 theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", ...fontFamily.sans]
      },
      colors: {
        transparent: "transparent",
        primary: "#cb3364",
        primary_light: "#b72e5a",
        secondary: "#52575c",
        light: {
          100: "#ffffff",
          200: "#f5f5f5",
          300: "#eeeeee",
          400: "#c0c1c3"
        },
        dark: {
          100: "#373c49",
          200: "#2c303a",
          300: "#21242c",
          400: "#16181d"
        }
      },
    },
```
_This issue is specific to this particular component because the developer who created it used color codes that do not align with the UI. I will take responsibility for resolving this issue by making the necessary adjustments to the component._
![image](https://github.com/lucavallin/first-issue/assets/91373023/1d6a6f2c-8873-4a44-a4a9-362cb49211be)

**@lucavallin . so How can I proceed with this issue?**

**Comment by lucavallin** [comment]
@Vivek-04022001 Let's way for this. Configuration improvements are not relevant right now because there is an incoming redesign anywhere. I would focus instead on the correctness of the classes we apply, e.g. are there more classes than needed? Are there classes on an element that provide conflicting styles?

**Comment by Vivek-04022001** [comment]
**🤷 @lucavallin, I've come across a component named SearchBar.tsx used within RepositoryList.tsx. It includes a hidden class that, when removed, reveals the search bar component.**
We should either remove the component or remove the 'hidden ' class.
![image](https://github.com/lucavallin/first-issue/assets/91373023/e962c84f-9f7f-4fcb-af7d-6d579c7ed413)

**Comment by lucavallin** [comment]
Hey @Vivek-04022001, yes, that is supposed to be hidden for the time being. #215 fixes that.
