### ISSUE TITLE
Fix sidebar for improved navigation

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#214]
The sidebar currently stays stuck at the top, so it is not visible anymore when scrolling through the list of repos. We should consider giving it a fixed position so it is always visible in the page.

**Comment by klouds27** [comment]
I was wondering if anyone is currently working on this? I'd be interested in taking a look.

**Comment by Vivek-04022001** [comment]
I want to work on this issue?

**Comment by shiwanhs05** [comment]
Please assign this issue to me, Thank you !

**Comment by lucavallin** [comment]
@Vivek-04022001 First one is fine. How does it work on mobile?

**Comment by Vivek-04022001** [comment]
@lucavallin, I haven't made any changes to the code for mobile devices. If you'd like, I can address this within the same pull request.

**Comment by lucavallin** [comment]
@Vivek-04022001 I think on mobile it can stay the same. Maybe we could add a button to scroll all the way back up again.

**Comment by Vivek-04022001** [comment]
Great idea! I'm going to start working on this right away.

**Comment by Vivek-04022001** [comment]
### Done 🫡
_My code is functioning correctly on mobile devices. However, I would appreciate your input regarding UI and design. Is there anything else I should consider or adjust?_

https://github.com/lucavallin/first-issue/assets/91373023/3d1809d4-011d-4dd8-97eb-41a377ff96db

**Comment by Vivek-04022001** [comment]
### Scroll to Top Feature Is Complete 🫡
1. The scroll button will only appear when the user reaches a certain height within the application.
2. Upon clicking the button, the user will be swiftly taken to the top position (top-0)  of the page.


https://github.com/lucavallin/first-issue/assets/91373023/4a6ff264-9cfa-48b4-a67a-26522b41e4b6

**Comment by lucavallin** [comment]
@Vivek-04022001 Both nice changes! I wonder if the button in video 2 is big enough? What is the recommended size for buttons on mobile?

**Comment by Vivek-04022001** [comment]
### SUGGESSTION 🧠
@lucavallin, kindly review these two sizes: "xl" and "2xl."1. xl

https://github.com/lucavallin/first-issue/assets/91373023/f7fd4fe9-7fe1-4ca4-afcb-18ee99dcb0a0


3. 2xl

https://github.com/lucavallin/first-issue/assets/91373023/a203f2cb-9cc9-415f-ae12-d0f4672a0482

Now, the important question is whether you would like me to extend the visibility of the scroll-to-top button to devices other than mobile. Currently, it's only visible on mobile devices.

**Comment by lucavallin** [comment]
@Vivek-04022001 Thanks! I think `xl` is fine. The current design is fine, I like the icon from the last image though!

**Comment by Vivek-04022001** [comment]
@lucavallin  do you want this button on all the devies ?

**Comment by lucavallin** [comment]
@Vivek-04022001 Sure, that's fine.

**Comment by Vivek-04022001** [comment]
### **🫡 All the work is not completed** 

@lucavallin, I've created a pull request (#240). Kindly take a look when you have some time available, and I would greatly appreciate your valuable feedback.
