### ISSUE TITLE
Inconsistent UI of RepositoryIssueNumberIndicator component - modify CSS

### ISSUE THREAD

**Issue by Bitnagar** [lucavallin/first-issue#216]
### Bug description
There is an inconsistency in the design of  [RespositoryIssueNumberIndicator](https://github.com/lucavallin/first-issue/blob/eee0dd4e54c0d0cee10962f1b81eeabfa4be5869/components/Repository/RepositoryIssueNumberIndicator.tsx#L6) component as shown below:

![inconsistent-ui-firstissue dev](https://github.com/lucavallin/first-issue/assets/88842947/cea22657-aed9-4d06-bcff-bde500b3db5c)

The current CSS of the component does not work for viewports lesser than 950px. (Please note that this component is hidden in smaller devices)

## Expected Behavior
The CSS should be fixed in order to maintain a consistent UI.

## Current Behavior
The current CSS of the component does not work for viewports lesser than 950px.

## Possible Solution
Fix the width and padding for the particular html element.

## Steps to Reproduce
Go to [firstissue.dev](https://www.firstissue.dev/) and resize the window to 950px.
Slowly start decreasing the size and observe the bug.

**Comment by Bitnagar** [comment]
Hey @lucavallin , If you consider this issue, please assign this to me so that i can make a PR for it. I have it fixed on my local.

**Comment by lucavallin** [comment]
@Bitnagar Assigned

**Comment by Bitnagar** [comment]
@lucavallin I have added the PR for it. Thanks for this wonderful project and opportunity to contribute. Please add the label `hacktoberfest` to this issue, so that it gets accepted. I really appreciate your time and efforts.🙏

**Comment by lucavallin** [comment]
@Bitnagar Thanks. It's merged.
