### ISSUE TITLE
Missing files - Respository best practices

### ISSUE THREAD

**Issue by Bitnagar** [lucavallin/first-issue#217]
This repo is missing some important files that are considered as OSS best practices. The files that i have listed below will improve the experience of the contributors and also will make sure the Hacktoberfest participants will get their PRs accepted.

Kindly add the following files in the repo:
- `Contributing.md`
- `Code of conduct.md`

----
#### I deeply appreciate the author and maintainers of this repo for their time and efforts. Thanks.

**Comment by lucavallin** [comment]
@Bitnagar Good one, I'll add it!

**Comment by lucavallin** [comment]
Done!
