### ISSUE TITLE
Proposal | Scrollbar color

### ISSUE THREAD

**Issue by ivanosquis10** [lucavallin/first-issue#218]
Hello, I hope you are feeling well. First I must say that I love the project, I've been waiting for a while to be able to contribute and I didn't see anything.

My proposal is to be in tune with the UI and the whole project, put color to the scroll bar so that it has more consistency on the web. Here I leave an image of the proposal:

![image](https://github.com/lucavallin/first-issue/assets/83567373/8a022446-5b70-4f01-a2df-f94f7743c90d)

**Comment by lucavallin** [comment]
Hey @ivanosquis10! Looks great - feel free to open a PR.

**Comment by Vivek-04022001** [comment]
@ivanosquis10 , can I contribute to this issue?

**Comment by lucavallin** [comment]
@Vivek-04022001 this has been merged already. @ivanosquis10 Thanks!
