### ISSUE TITLE
🐛 Bug Report: JOIN THE NEWSLETTER UI Enhancement

### ISSUE THREAD

**Issue by nishitxmehta** [lucavallin/first-issue#222]
# 🐛 Bug description

The **Text Box** and **Join** button coincide with each other at the end and starting respectively. Below are the Screenshots as a proof.
## Screenshots

![Screenshot](https://github.com/lucavallin/first-issue/assets/80708599/6b029aca-9acc-4b34-bf93-e8fe204ca09b)

![Screenshot](https://github.com/lucavallin/first-issue/assets/80708599/c5b090eb-e1c5-4f25-8277-7c6310cda967)

## ✨ It would be nice

- If there's some gap between the **Text Box** and **Join** button.
- To change `mail` icon color in the **Text Box** from ![#52575C](https://via.placeholder.com/10/52575C?text=+) #52575C to ![#CB3364](https://via.placeholder.com/10/CB3364?text=+) #CB3364.

## 👀 Have you spent some time to check if this issue has been raised before?

 - [x] I checked and didn't find similar issue.
## 🏢 Have you read the Code of Conduct?
- [x] I have read the [Code of Conduct](https://github.com/lucavallin/first-issue/blob/main/CODE_OF_CONDUCT.md).

**Comment by nishitxmehta** [comment]
Hey @lucavallin , If you consider this issue, please assign this to me so that I can make a PR for it.

**Comment by lucavallin** [comment]
Hey @nishitxmehta, thanks for the issue! I am about to replace that component with another provider, so no work needed here this time.
