### ISSUE TITLE
 The sidebar menu on mobile devices should automatically collapse after redirecting to the desired page. 

### ISSUE THREAD

**Issue by Vivek-04022001** [lucavallin/first-issue#227]
### Issue Description:

_Currently, our web application's sidebar menu remains expanded even after users navigate to their desired pages. This poses a usability challenge, especially on smaller screens where the sidebar occupies valuable screen real estate._

Importance
1. Reduced Cognitive Load: A collapsed sidebar reduces cognitive load as users don't have to manage an open sidebar when navigating through different sections of the application.
2. Consistency: It aligns with best practices and user expectations, as many websites and applications implement this behavior for a cleaner and more intuitive interface.
3. Enhanced User Experience: Automatically collapsing the sidebar after redirection enhances the user experience. Users can focus on the content of the newly visited page without the distraction of a persistent open sidebar.
4.Optimal Use of Screen Space: On smaller devices, screen space is limited. Collapsing the sidebar maximizes the available space for the main content, improving readability and usability.

Demo of the issue:

https://github.com/lucavallin/first-issue/assets/91373023/1c3797da-6741-4fad-ad2f-9404d813ed56

**Comment by raaaaj214** [comment]
can i take this issue ?

**Comment by raaaaj214** [comment]
the video shared above , is not loading

**Comment by raaaaj214** [comment]
hey this is my first time contributing , so i guess I have made a pull request although it says there that authorization is required, i don't know if i have to do it or it will be done by the moderators , I will be more than happy if you can guide me.

**Comment by Bitnagar** [comment]
@raaaaj214 Your PR changes nothing and is a Spam PR. Spam PRs will not be tolerated. Kindly respect the time and effort of owner and maintainers of this repo. Please send these type of PR to your own personal repositories if you want to learn the basics.

First time contributions are exciting and newbies forget to follow ethics. Before making a PR, wait for the issue to get assigned to you unless specified by owner/maintainer in contributing file or elsewhere.

Kindly do not spam. Learn best practices and become a great contributor!

**Comment by raaaaj214** [comment]
i apologize for my mistake, please assign me this issue so i can create a pull request

**Comment by lucavallin** [comment]
@Bitnagar no need to be harsh, I trust @raaaaj214 has good intentions and is interested in learning about the project and the processes around it. [We as members and contributors, and leaders pledge to make participation in our community a pleasant experience for everyone, interacting in ways that contribute to a welcoming and healthy community.](https://github.com/lucavallin/first-issue/blob/main/CODE_OF_CONDUCT.md)

@raaaaj214 Feel free to investigate this and open a PR once you have it working. I marked your current PR as draft in the meantime.

**Comment by raaaaj214** [comment]
what if after collapsing we only show the tags that have been selected and hide all the other tags

**Comment by Bitnagar** [comment]
@lucavallin i apologise for it. I forgot to choose the right words for explaining. Will surely keep this mind.

I was seeing a lot of spam PRs during hacktoberfest and didn't want that to happen here. I got carried away in that and forgot that this might be the way for someone to get started.

**Comment by Vivek-04022001** [comment]
_**@lucavallin, I'd like to respectfully present my perspective on this matter. When a user attempts to select options from both the Language and Tag Picker sections and subsequently clicks on any button, the page redirects. However, we encounter a situation where both the Language Picker and Tag Picker sections remain open, causing a reduction in the available space for viewing results.

To optimize the user experience, I propose that upon redirecting to a new page, the Language Picker and Tag Picker components automatically collapse. This adjustment ensures that users do not need to manually close these components since they have already made their selections. This change aims to enhance usability and streamline the user's interaction with the platform. Your consideration of this suggestion is greatly appreciated.**_

### 🫡 I'm interested to work on this issue please assign to me.

**Comment by lucavallin** [comment]
@Vivek-04022001 looks good, go ahead!

**Comment by Muhammad-Tayyab-Bhutto** [comment]
@lucavallin kindly check out my request for merge if is right to merge. Thanks
