### ISSUE TITLE
include projects with more than 50 contributors

### ISSUE THREAD

**Issue by robstoll** [lucavallin/first-issue#239]
As suggested here: https://github.com/lucavallin/first-issue/pull/230 I am opening this issue. I think it makes sense to include projects which clearly welcome contributors and IMO a project with more than 50 contributors is eligible.

**Comment by RajuGangitla** [comment]
can you assign this issue to me

**Comment by lucavallin** [comment]
@robstoll Thanks for opening the issue. 
@jeffreyaven and @zillemarco might be interested too.
@RajuGangitla Sorry, assigned to myself, this is more of a "executive" decision.

The current criteria are in place to avoid projects like "my cousin's twitter clone" with 100 stars and 10 contributors... I want users to go to `firstissue.dev` and be certain that whatever repo they open, they'll find a cool and important one to contribute. Therefore, how can we select for "significance" for the community in a unequivocal and enforceable way?

**Comment by robstoll** [comment]
In my experience, the most important part for newcomers/first issue solvers is the support from the contributors when they try to tackle an issue. This has more to do with quality and not with quantity and is harder to track. A good experience will motivate them more to continue contributing (to open source) than 1000 stars I would say.

But as said, quality is harder to track and I get that you want kind of substitute that with numbers. I think 50 contributors says as much as 1000 stars but you could combine it with further criteria if you like. In the end the point about 1000 stars and 10 contributors could look as follows (in the PR template)

- [ ] Either:
     - [ ] At least 10 contributors and 1000 stars 
     - [ ] At least 50 contributors and 250 stars
     - [ ] At least 50 contributors and 100 stars and 10 watchers
     - [ ] ...
