### ISSUE TITLE
Intermittent Unknown Collapse Issue in Repository Section

### ISSUE THREAD

**Issue by Vivek-04022001** [lucavallin/first-issue#250]
**I've noticed an issue within the repository section. When attempting to collapse it, sometimes it successfully collapses, but at other times, it unexpectedly navigates to the repository on GitHub. 

demo: 

https://github.com/lucavallin/first-issue/assets/91373023/feaa4256-d080-42cb-a79f-da88a3312266

**Comment by Muhammad-Tayyab-Bhutto** [comment]
@lucavallin should I fix it

**Comment by lucavallin** [comment]
@Muhammad-Tayyab-Bhutto Go ahead!

**Comment by Vivek-04022001** [comment]
@lucavallin, could you please assign this task to me? It's been a week since the previous assignee didn't provide any code for this issue.

**Comment by Vivek-04022001** [comment]
@lucavallin I have solve this issue and raise a new pull request . Please have a look #267
