### ISSUE TITLE
Repository item layout appears to be broken for screen sizes below extra large

### ISSUE THREAD

**Issue by nabarvn** [lucavallin/first-issue#251]
This is how it looks on a small width device (e.g. mobile phone):

![Repository Item Issue (sm)](https://github.com/lucavallin/first-issue/assets/64539836/919749b5-0183-4563-a08a-9addbfcd7926)

This is how it looks on a medium width device (e.g. iPad in vertical orientation):

![Repository Item Issue (md)](https://github.com/lucavallin/first-issue/assets/64539836/9ac5960d-6e22-489b-96e8-15066f95e234)

This is how it looks on a large width device (e.g. iPad in horizontal orientation or a smaller size laptop screen):

![Repository Item Issue (lg)](https://github.com/lucavallin/first-issue/assets/64539836/4a4370fc-5e5e-4fd1-8b6d-7aaee52f335a)

The issue can be readily reproduced by utilizing Google Chrome Developer Tools, although it's important to note that not all repository items exhibit this behavior.

I'd love to take the lead on this if you're open to it, @lucavallin.

**Comment by lucavallin** [comment]
@nabarvn Go for it!
