### ISSUE TITLE
A small detail in the floating buttons :)

### ISSUE THREAD

**Issue by ivanosquis10** [lucavallin/first-issue#263]
Hi, I hope you are well, I have already contributed to this project, for now it has been small things and I bring you another one (in my case I feel it doesn't look good). And it is that these buttons are not aligned, I feel that if they were well aligned in desktop view, it would be great. In mobile if they are well aligned. I don't know if this is done on purpose, in that case close the issueeee, thank u

![image](https://github.com/lucavallin/first-issue/assets/83567373/8d948494-a1aa-409e-a1c9-88b0bb8d1000)

**Comment by ivanosquis10** [comment]
![image](https://github.com/lucavallin/first-issue/assets/83567373/1203cf11-dc1b-48b0-9e35-5e773c3f855c)

**Comment by lucavallin** [comment]
Looks good, feel free to open a PR! How will it look on mobile?

**Comment by ivanosquis10** [comment]
looks nice, and okay, i'll <3
![image](https://github.com/lucavallin/first-issue/assets/83567373/37bdf01c-6201-4afd-8646-241d744bc6b3)
