### ISSUE TITLE
Create search page

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#31]
We should consider adding a search page (and a search bar). When a user enters a search string, we can look for matches in languages, topic, repository's owner - name - description - topics - issues.

I already did some groundwork in `/pages/search/[tag].tsx` but not much else. I can foresee this search to be a bit slow (since it's a static website it will have to be done via JS, in-memory, by checking arrays in a for loop).

**Comment by FranciscoPachec0** [comment]
Hey, I'm currently looking into this issue but as I understood the search part (on the /pages/search/[tag].tsx) is almost complete right? So it's only missing the search bar?

**Comment by lucavallin** [comment]
Hey @FranciscoPachec0! That's correct, I quickly put together the search component long ago, I am not sure I tested it, but as you say, the main thing that's missing is the search bar!
