### ISSUE TITLE
Update the README.md in the How Does It Work? Section

### ISSUE THREAD

**Issue by thebarshablog** [lucavallin/first-issue#34]
After going through the README.md, I came across that firstissue is based on goodfirstissue. Bringing beginner-friendly issues to open-source newbies is an appreciated effort. However, I believe we can add tutorials/screenshots/videos/guides to the How It Works? section so that we truly accompany beginners to make their first contribution with us! @lucavallin

**Comment by durosly** [comment]
That is a great idea. I would like to handle that.

**Comment by thebarshablog** [comment]
> That is a great idea. I would like to handle that.

Amazing. Do you mind if we co-work together on this?

**Comment by durosly** [comment]
I don't mind. I would love that

**Comment by durosly** [comment]
How do we get this show on the road?

**Comment by thebarshablog** [comment]
![How Does It Work-firstissue](https://user-images.githubusercontent.com/103309340/211241224-16b75c76-6e85-464b-9669-ce6bbbd166b0.png)

I believe we should add screenshots in every step to show how it's actually done. I mean the setup and the installation. And also, to help beginners get onboarded on their first open source contribution, we must also show them how to find repositories that fit our criteria and add it to the .json file

**Comment by durosly** [comment]
Ok, so it's a three stage process.

1. How to setup the project in their local machine
2. How to make their contributions but in accordance to the project standard
3. How to make a PR

Right?

**Comment by thebarshablog** [comment]
> Ok, so it's a three stage process.
> 
> 1. How to setup the project in their local machine
> 2. How to make their contributions but in accordance to the project standard
> 3. How to make a PR
> 
> Right?

Yes!

**Comment by durosly** [comment]
Nice

**Comment by Atul8766** [comment]
I want to work on this issue and am also a beginner can you please assign the task to me?

**Comment by durosly** [comment]
Let's work on it together then @Atul8766 
It may seem as @thebarshablog is busy

**Comment by thebarshablog** [comment]
> Let's work on it together then @Atul8766 
> It may seem as @thebarshablog is busy

@durosly Atul and you are welcome to begin on this. Count me in, after February 16. Thanks. Let me know anything you may require.

**Comment by Atul8766** [comment]
@durosly so should I start the first task from your given 3 steps that is how to setup the project locally on our local machine if it seems ok then let me know.

**Comment by Atul8766** [comment]
[README.md](https://github.com/lucavallin/first-issue/files/10660500/README.md)
please check this file and tell me what should i change in this file to make it more suitable.

**Comment by thebarshablog** [comment]
@Atul8766 if I may suggest, begin with recording a video/ using screenshot on how they can contribute to this file? Show them how's it done.

**Comment by Atul8766** [comment]
if I use a screenshot, how can I tell every single step by writing a document or do you have any better idea?

**Comment by Atul8766** [comment]
@thebarshablog if I use a screenshot, how can I tell every single step by writing a document or do you have any better idea?

**Comment by thebarshablog** [comment]
@Atul8766 You may take snapshots of how each step of contribution looks and accordingly write the documentation. Kindly give each suggestions some evaluation time, try and test out and revert with queries. 
Or, you may consider making a tutorial video on how a contribution can be made to the list of repositories and create a pull request for Luca to judge.

**Comment by Atul8766** [comment]
@thebarshablog I think making a tutorial video is a good idea it can help beginners easily understand am I right?

**Comment by thebarshablog** [comment]
@Atul8766 Firstly, I've given this as a suggestion earlier. To answer to your question, it depends on people. Some people prefer written documentation, while some go for video tutorial. Pick one, at the moment, either writing the documentation or prepare a video tutorial.

**Comment by Atul8766** [comment]
@thebarshablog so at this moment, I think writing documentation is good later if we face any feedback so I can also make the tutorial video am I right?

**Comment by thebarshablog** [comment]
> @thebarshablog so at this moment, I think writing documentation is good later if we face any feedback so I can also make the tutorial video am I right?

Your choice.

**Comment by lucavallin** [comment]
All good ideas! My preference goes for written documentation.

**Comment by Atul8766** [comment]
@lucavallin Added some steps how to contribute on project #57 I make PR please checkout and let me know if any changes I have to make
