### ISSUE TITLE
schedule-deploy workflow does not work

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/first-issue#36]
The `schedule-deploy` workflow at https://github.com/lucavallin/first-issue/blob/main/.github/workflows/schedule_deploy.yml is used to run the `Deploy to firstissue.dev` once a day: it fetches new data and deploys to the website. Unfortunately the script it runs is rate-limited by GitHub after just a few calls when the pipeline is triggered by `schedule-deploy`. I think this might be due to some token not being set properly for `schedule-deploy`.

**Comment by lucavallin** [comment]
@thebarshablog @Atul8766 This is a high priority one if you're looking for something else to contribute to :)

**Comment by thebarshablog** [comment]
> @thebarshablog @Atul8766 This is a high priority one if you're looking for something else to contribute to :) 

I'll surely look into this issue. 

I'm occupied till February 15, post which I will look into. 
Thanks, anyway ☺️

**Comment by Atul8766** [comment]
> @thebarshablog @Atul8766 This is a high priority one if you're looking for something else to contribute to :) 

Ya sure I will try to contribute to this issue also but let me first understand this issue deeply.

Thanks for recommending.

**Comment by lucavallin** [comment]
Fixed.
