### ISSUE TITLE
Misspelled file name

### ISSUE THREAD

**Issue by isaacwashere** [lucavallin/first-issue#76]
### General
The file `ReposiroryIssueNumberIndicator.tsx` should be renamed `RepositoryIssueNumberIndicator.tsx`. I don't know how I missed this (considering I have spell check in my VSCode 😅 ). I introduced this file, in this PR #69 🤦‍♂️ (sorry about that 😞 ) . 

The actual component in the file has the correct name, it's just the file name that's incorrect, along with the import statement in `RepositoryItemTopBar.tsx`.

**Comment by lucavallin** [comment]
Can happen! Feel free to open a PR to address that.

**Comment by isaacwashere** [comment]
Okay, I'll put a PR up for this in a moment 👍

**Comment by VhalennnG** [comment]
hii, i've fix the name, but when i run "npm install", it's pretty much diffrent with yours, is it okay??

**Comment by isaacwashere** [comment]
@VhalennnG Hmm, it looks like you may have done duplicate work. Out of curiosity, did you miss the PR that I put up completing this issue?

**Comment by VhalennnG** [comment]
Thank you sir

Pada tanggal Sab, 1 Apr 2023 23.45, Luca Cavallin ***@***.***>
menulis:
